fix(html5): fix useUserCameraDomElement behavior and did some refactor
bigbluebutton/bigbluebutton-html-plugin-sdk pull request #110
Opened 2024-08-22 14:12 UTC by GuiLeme

### What does this PR do?

- Adds new extensible area: userCameraHelper (which is a button added in one of the corners of the user camera);
- Fixes useUserCameraDomElement (the issue was that when a new user enters the room, the dom-element-manipulator hook didn't return the elements);
- Adds a click event to the arguments of the onClick callback function of screenshareHelper;
- Refactors naming of plugin hook events so as to add new event informing bbb-core that the plugin is changing something on its side; 

### More

This PR is closely related to the CORE PR https://github.com/bigbluebutton/bigbluebutton/pull/21004

See a demo of the new userCameraHelper down below:

![image](https://github.com/user-attachments/assets/9e9b0f21-0c69-47ab-8a1f-fc029f9be05b)

2024-08-26 18:18 UTC, Arthurk12 requested changes
One thing to note is that, unlike with messages where it’s possible to identify the message IDs returned by the `useChatMessageDomElements `hook using the [`data-chat-message-id`](https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/blob/49316715ce501953d06b25f39ee0b304ec31fce3/samples/sample-server-commands-plugin/src/components/sample-server-commands-plugin-item/component.tsx#L88) attribute, this is not possible for cameras/streams. I wonder if, instead of adding this analogous attribute to camera elements, it might be more appropriate to change the return of these DOM hooks to an array of objects containing the DOM element and the ID. Something like: `{ domElement, id }`.

2024-08-26 18:25 UTC, Arthurk12 commented
Actually, the [docs for these two hooks state](https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/blob/49316715ce501953d06b25f39ee0b304ec31fce3/src/core/api/types.ts#L211-L229) that they return an array of objects just like mentioned above.

2024-09-03 14:43 UTC, GuiLeme commented
> it might be more appropriate to change the return of these DOM hooks to an array of objects containing the DOM element and the ID

As discussed internally, this won't be necessary since the ID of the dom element is not previously available for the developer to filter (or mapping, flat-mapping...) using it. The streamId, on the other hand, is now available within the user-camera helper button as an option for this suggestion.

2024-09-10 17:54 UTC, Arthurk12 approved these changes
LGTM.

2024-09-10 18:18 UTC, merged