feat(generic-content): allow injecting generic content in the sidekick panel
bigbluebutton/bigbluebutton-html-plugin-sdk pull request #88
Opened 2024-06-10 23:10 UTC by Arthurk12

## What does this PR do?

This PR implements the feature to allow injecting generic content to the sidekick panel.
Specifically, this PR:
- Renames all occurrences of 'generic-component' to 'generic-content'
- Adds 2 types of 'generic-content':
   1. `MAIN_CONTENT`: Displayed over the presentation area
   2. `SIDEKICK_CONTENT`: Displayed in the sidekick panel when the associated button is clicked 
- Maps the already existing generic-component to generic-content of type `MAIN_CONTENT`
- Ensures that each injected generic sidekick content is automatically associated with a button in the navigation sidebar to toggle its panel.
- Adds a simple sample showcasing how to use the generic sidekick content
![generic-content-sidekick-sample](https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/assets/32987232/9378afe1-a64c-4df7-b142-db1caa940dcc)

HTML5 related part: 

### What is still missing?
- Grouping navigation sidebar buttons of generic contents by section name.
- Enabling/disabling the three dots in the top right corner of the panel, as well as injecting buttons.

### Closes
Closes #76

2024-06-12 11:00 UTC, TiagoJacobs requested changes

2024-06-12 11:13 UTC, TiagoJacobs requested changes
Thanks for this contribution, I've added a few comments in the code.

2024-06-14 13:40 UTC, Arthurk12 commented on samples/sample-generic-sidekick-content-plugin/README.md
> +Where `<<PLUGIN_URL>>` is the URL that points to the location where your bundled `SampleGenericSidekickContentPlugin.js`-file is hosted.
I've looked into the new README format, and it seems to me that it is already being used here.

2024-06-14 17:39 UTC, GuiLeme approved these changes
LGTM

2024-06-14 17:48 UTC, merged